import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Gui extends javax.swing.JFrame {

    // Constructor. Call initComponents() and make input fields invisible.
    public Gui() {
        initComponents();
        jLabel1.setVisible(false);
        jFirstName.setVisible(false);
        jLabel2.setVisible(false);
        jLastName.setVisible(false);
        jLabel3.setVisible(false);
        jPhone.setVisible(false);
        jLabel4.setVisible(false);
        jRoomBox.setVisible(false);
        jLabel5.setVisible(false);
        jBreakBox.setVisible(false);
        jLabel6.setVisible(false);
        jArrival.setVisible(false);
        jLabel7.setVisible(false);
        jDeparture.setVisible(false);
        jButtonInsert.setVisible(false);
        
        jSearchCrit.setVisible(false);
        jSearchButton.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jSearchArr.setVisible(false);
        jSearchDep.setVisible(false);
        jSearchFName.setVisible(false);
        jSearchLName.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
    }

    // Code generated by Netbeans GUI builder. It defines the frame, the text fields, the buttons etc.
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRoomBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jBreakBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jArrival = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDeparture = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSearchButton = new javax.swing.JButton();
        jSearchCrit = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSearchFName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSearchLName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSearchArr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSearchDep = new javax.swing.JTextField();
        jClearInsertButton = new javax.swing.JButton();
        jClearSearchButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Telephone");

        jLabel4.setText("Room type");

        jRoomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        // jRoomBox.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         jRoomBoxActionPerformed(evt);
        //     }
        // });

        jLabel5.setText("Breakfast");

        jBreakBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jLabel6.setText("Arrival (dd-mm-yyyy)");

        // jArrival.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         jArrivalActionPerformed(evt);
        //     }
        // });

        jLabel7.setText("Departure (dd-mm-yyyy)");

        jButtonInsert.setText("Save record");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButton1.setText("Add new record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Show Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jSearchCrit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Date" }));

        jLabel8.setText("First Name");

        jSearchFName.setColumns(6);

        jLabel9.setText("Last Name");

        jSearchLName.setColumns(6);

        jLabel10.setText("Arrival (dd-mm-yyyy)");

        jSearchArr.setColumns(10);
        // jSearchArr.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         jSearchArrActionPerformed(evt);
        //     }
        // });

        jLabel11.setText("Departure (dd-mm-yyyy)");

        jSearchDep.setColumns(10);

        jClearInsertButton.setText("Clear");
        jClearInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearInsertButtonActionPerformed(evt);
            }
        });

        jClearSearchButton1.setText("Clear");
        jClearSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearSearchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jClearInsertButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jRoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBreakBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDeparture, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jArrival, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jClearSearchButton1)
                            .addComponent(jSearchCrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jSearchDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jSearchFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jSearchLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClearInsertButton)
                            .addComponent(jClearSearchButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBreakBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSearchCrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSearchFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSearchLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSearchArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearchDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonInsert)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jSearchButton)
                        .addGap(96, 96, 96))))
        );

        pack();
    }// </editor-fold>                        
                                     

    // Enabled when 'Save record' is clicked.
    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Get the values of the input textfields.
        String firstName = jFirstName.getText();
        String lastName = jLastName.getText();
        String phone = jPhone.getText();
        String roomType = jRoomBox.getItemAt(jRoomBox.getSelectedIndex());
        String breakfast = jBreakBox.getItemAt(jBreakBox.getSelectedIndex());
        String arrival = jArrival.getText();
        String departure = jDeparture.getText();
        
        boolean breakfastBoolean = (breakfast.equals("Yes")) ? true : false;
        
        // Create a new Reservation object
        ArrayList<Reservation> resvs = new ArrayList<Reservation>();
        Reservation res = new Reservation(firstName, lastName, phone, roomTypeNumber(roomType), breakfastBoolean, arrival, departure);
        // Save it to the file only if it is valid. (Valid date, name an phone)
        if (res.isValid()){
            resvs.add(res);
        }             
        
        Reservation.append(Reservation.file_name, resvs);
        
        // Clear the input textfields
        jFirstName.setText("");
        jLastName.setText("");
        jPhone.setText("");
        jArrival.setText("");
        jDeparture.setText("");
    }                                             
                                     
    // Input textfields appear when 'Insert record' is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                
        jLabel1.setVisible(true);
        jFirstName.setVisible(true);
        jLabel2.setVisible(true);
        jLastName.setVisible(true);
        jLabel3.setVisible(true);
        jPhone.setVisible(true);
        jLabel4.setVisible(true);
        jRoomBox.setVisible(true);
        jLabel5.setVisible(true);
        jBreakBox.setVisible(true);
        jLabel6.setVisible(true);
        jArrival.setVisible(true);
        jLabel7.setVisible(true);
        jDeparture.setVisible(true);
        jButtonInsert.setVisible(true);
    }                                        

    private void display_results(ArrayList<Reservation> results){
        // Frame initialization
        JFrame f = new JFrame();
 
        // Frame Title
        f.setTitle("Reservations found");
 
        // Column Names
        String[] columnNames = { "First Name", "Last Name", "Phone", "Room type",
            "Breakfast", "Arrival", "Departure", "Total cost"
        };
        
        // Create a tableModel to add data in the table
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        
        for (Reservation resv : results){
            String firstName = resv.getFirstName();
            String lastName = resv.getLastName();
            String phone = resv.getPhone();
            String roomType = resv.getRoomType();
            boolean breakfast = resv.getBreakfast();
            String arrival = resv.getArrival();
            String departure = resv.getDeparture();
            int cost = resv.get_cost();
            
            // Get reservation info from each Reservation object and add it to the tableModel
            Object[] row = {firstName, lastName, phone, roomType, breakfast, arrival, departure, cost};
            tableModel.addRow(row);
        }
        
        JTable j = new JTable(tableModel); // Create a table using the tableModel
 
        // Initializing the JTable
        j.setBounds(100, 100, 600, 300);
 
        // adding it to JScrollPane
        JScrollPane sp = new JScrollPane(j);
        f.add(sp);
        // Frame Size
        f.setSize(600, 200);
        f.setBounds(100, 100, 700, 400);
        // Frame Visible = true
        f.setVisible(true); 
    }    
    
    // Load data from the file and search the records based on Name or Date
    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // get the selected value in the dropdown list
        String searchCriterion = jSearchCrit.getItemAt(jSearchCrit.getSelectedIndex());
        
        ArrayList<Reservation> found = new ArrayList<Reservation>();
        // If 'Name' is selected, search by name
        if (searchCriterion.equals("Name")){
            String firstName = jSearchFName.getText();
            String lastName = jSearchLName.getText();
            found = Reservation.searchByName(Reservation.file_name, firstName, lastName);
        }
        // If 'Date' is selected, search by date
        else{
            // Check if requested date is valid
            try{
                LocalDate arrival = LocalDate.parse(jSearchArr.getText(), Reservation.dtf);
                LocalDate departure = LocalDate.parse(jSearchDep.getText(), Reservation.dtf);          
                found = Reservation.searchByDate(Reservation.file_name, arrival, departure);
            }
            catch (DateTimeParseException x){
                Reservation.errorDialog("Please enter a valid date");;
            }
            
        }
        
        // Display results in a table
        display_results(found);

        jSearchFName.setText("");
        jSearchLName.setText("");
        jSearchArr.setText("");
        jSearchDep.setText("");
    }                                             

    // Input textfields for searching appear
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jSearchCrit.setVisible(true);
        jSearchButton.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jSearchArr.setVisible(true);
        jSearchDep.setVisible(true);
        jSearchFName.setVisible(true);
        jSearchLName.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
    }                                        

    // Input textfields for searching disappear
    private void jClearSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        jSearchCrit.setVisible(false);
        jSearchButton.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jSearchArr.setVisible(false);
        jSearchDep.setVisible(false);
        jSearchFName.setVisible(false);
        jSearchLName.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
    }                                                   

    // Input textfields for inserting disappear
    private void jClearInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        jLabel1.setVisible(false);
        jFirstName.setVisible(false);
        jLabel2.setVisible(false);
        jLastName.setVisible(false);
        jLabel3.setVisible(false);
        jPhone.setVisible(false);
        jLabel4.setVisible(false);
        jRoomBox.setVisible(false);
        jLabel5.setVisible(false);
        jBreakBox.setVisible(false);
        jLabel6.setVisible(false);
        jArrival.setVisible(false);
        jLabel7.setVisible(false);
        jDeparture.setVisible(false);
        jButtonInsert.setVisible(false);
    }                                                  
                                
    private short roomTypeNumber(String roomType){
        short type = 0;
        switch (roomType){
            case "Single":
                type = 1;
                break;
            case "Double":
                type = 2;
                break;
            case "Triple":
                type = 3;
        }
        return type;
    }
    
    // Main methods, generated by netbeans
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField jArrival;
    private javax.swing.JComboBox<String> jBreakBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jClearInsertButton;
    private javax.swing.JButton jClearSearchButton1;
    private javax.swing.JTextField jDeparture;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName;
    private javax.swing.JTextField jPhone;
    private javax.swing.JComboBox<String> jRoomBox;
    private javax.swing.JTextField jSearchArr;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JComboBox<String> jSearchCrit;
    private javax.swing.JTextField jSearchDep;
    private javax.swing.JTextField jSearchFName;
    private javax.swing.JTextField jSearchLName;
    // End of variables declaration                   
}
